# Literature

Here is a review of existing methods, directly quoted from [@lewis_method_1903]. Each line from the pdf is a line here; maybe this makes editing easier? harder?

 I REGARD the teaching of English literature and the teaching
 of spelling, grammar, and rhetoric as two different professions.
 It is in many respects unfortunate that both should have to be
 practiced by a single teacher, or a single department, for the
 best teacher of literature may be the worst teacher of spelling,
 grammar, and rhetoric; but, as our curriculums are at present
 ordained, we have to face the situation as best we can. Let us
 frankly recognize, however, that we are dealing with two widely
 different sets of subjects; that the methods that succeed in the
 teaching of spelling and grammar may fail utterly with litera-
 ture; and that experience gained in one branch cannot be an
 infallible guide in the other.
 My own experience has been almost wholly in the teaching
 of literature, and methods of elementary instruction in that
 branch will be the subject of this paper. I wish, however, by
 way of preface, and in order to avoid a possible misunderstand-
 ing, to state briefly an opinion concerning both branches.
 There is much complaint against the manner in which kinder-
 garten ideas have invaded secondary schools and colleges. I
 hear it said that we do not discipline our scholars enough; and
 that that is why they are growing up illiterate. Now, my
 opinion is that, in so far as this complaint relates to our teaching
 of spelling, grammar, and rhetoric, it is not without foundation;
 I believe that in those subjects some of us do trust too much to
 Kindergarten methods-to literary methods; and I am glad to
 see a revival of the good old-fashioned discipline. On the other
 hand, in the teaching of English literature I think the idea of
 discipline is already carried rather too far, and that our schools
 and colleges would do better if they employed less of what is
 commonly called discipline than they actually do. In this paper
 I propose to defend what to many will seem altogether too lax a 
 method; but I wish it distinctly understood that I am referring
 only to the teaching of literature, and that, if I were discussing
 spelling, grammar, or rhetoric, I should speak very differently.
 The first problem that caused me much trouble in my own
 experience was as to the degree of minute thoroughness desirable
 in reading. The.average student has a very small vocabulary,
 and, of course, we want him to extend it. Suppose you are
 teaching Macbeth. Your first lesson brings you to Paddock,
 Graymalkin, kerns, gallowglasses, Bellona's bridegroom, and a
 score or more of other expressions that your student may not
 know unless he looks them up; and, of course, he will not look
 them up unless you make him-that is, unless you devote much
 of your time to quizzing the class upon particular words, and
 insist upon having everything explained.
 Of course, the objection to such a plan is the dryness of the
 toil involved. Our average student finds it a positively repellent
 task, and our object is to make literature attract him. On the
 other hand, if you do not make him look up the words he does
 not know, will he know Shakespeare at all ? How much of the
 exquisite beauty of Romeo, how much of the sublimity of Lear,
 is wholly lost upon the student who has not studied Shakes-
 peare's language. For every difficulty that you pass over in
 silence, you will inevitably feel a sting of conscience, and toward
 every student with whom you practice the laxer method you will
 have moments of feeling yourself a criminal.
 Nevertheless, after some years of varied experiments and after
 much reflection, I have long since abandoned the stricter method,
 and for the last three or four years I have been adding to the
 burdens of my conscience about three hundred crimes per
 annum. It is true that I feel, after teaching Hamlet, or Lear, or
 Othello, that none of my students really know Shakespeare; but,
 then, who does ? They cannot know him except in part, and
 the question for the teacher to decide is: What part? I
 have satisfied myself that, so far as my own younger students
 are concerned, they will know less about him if they are forced
 to read him in what I should call a thorough manner than if they
 are let off more easily. In the former case,
  assuredly not like him; and the knowledge of Shakespeare
 possessed by anybody who does not like him must of necessity
 be of small value.
 This seems but a superficial argument; but there is a deeper
 principle underlying it. Let us look at the question in another
 way. Let us suppose that our chief interest is merely to increase
 the student's vocabulary. Even so, I think it might be plausibly
 urged that the best way to accomplish this is not by making him
 study words. He will enrich his vocabulary more by wide read-
 ing than by thorough reading. Consider how we ourselves have
 learned the language. I have no idea how large my effective
 vocabulary is, but I am certain that not more than I per cent. of
 it consists of words that I have looked up. And, moreover, in
 a matter of this kind, it will not do to count merely the numbers
 of words that we know. The quality of our knowledge is more
 important to us than the quantity. From dictionaries and text-
 books I have learned such words as "sclerosis," "kilogram,"
 "epistemological," " isogeotherm," " dicotyledinous." A friend
 of mine has recently acquired the word " radiomicrometer," and
 he has three times in the last fortnight introduced it casually
 into conversation about the weather, with excellent effect. Such
 words as these are showy things to wear on the outside, but the
 part of our vocabulary that furnishes the really vital garment for
 our thought is the integument that grows by nature. Compare
 with the words that I have just listed such words as "father,"
 "mother." They afford an extreme example, for they suggest
 ideas that are more vitally dear to us than all the radiomicrome-
 ters in the world; but in a lower degree I think all the words
 that we have unconsciously absorbed, either from the speech of
 others or from our own discursive reading, are likewise more
 intimately ours than those we have exhumed by a deliberate
 effort from dictionaries.
 I myself, therefore, have discontinued that method of teach-
 ing English, because it seemed to me a misguided attempt to
 find a short-cut to culture.
