# Applications

Some _significant_ applications are demonstrated in this chapter.

## Example one

Brutus speaks [@mphillips_julius_2017]

It must be by his death. And for my part
I know no personal cause to spurn at him,
But for the general. He would be crowned:
How that might change his nature, there’s the question.
It is the bright day that brings forth the adder,
And that craves wary walking. Crown him that,
And then I grant we put a sting in him
That at his will he may do danger with.
Th’ abuse of greatness is when it disjoins
Remorse from power. And, to speak truth of Caesar,
I have not known when his affections swayed
More than his reason. But ’tis a common proof
That lowliness is young ambition’s ladder,
Whereto the climber-upward turns his face;
But, when he once attains the upmost round,
He then unto the ladder turns his back,
Looks in the clouds, scorning the base degrees
By which he did ascend. So Caesar may.
Then, lest he may, prevent. And since the quarrel
Will bear no color for the thing he is,
Fashion it thus: that what he is, augmented,
Would run to these and these extremities.
And therefore think him as a serpent’s egg,
Which, hatched, would, as his kind, grow mischievous,
And kill him in the shell.

## Example two

[Source]http://www.elsewhere.org/journal/pomo/1329856939/)

###Realism and material posttextual theory

Michel G. Scuglia
*Department of Future Studies, University of Western Topeka*
V. Linda Hanfkopf
*Department of Literature, Miskatonic University, Arkham, Mass.*

#### Contexts of absurdity

“Society is part of the genre of culture,” says Sartre. However, Lyotard
uses the term ‘the neocapitalist paradigm of narrative’ to denote the failure
of cultural art.

The characteristic theme of Werther’s[1] analysis of
material posttextual theory is the difference between society and sexual
identity. If the neocapitalist paradigm of narrative holds, we have to choose
between cultural materialism and neosemiotic textual theory. In a sense, Debord
suggests the use of the neocapitalist paradigm of narrative to attack and
analyse class.

“Sexual identity is fundamentally dead,” says Baudrillard; however,
according to Tilton[2] , it is not so much sexual identity
that is fundamentally dead, but rather the futility, and therefore the
meaninglessness, of sexual identity. Wilson[3] holds that
the works of Smith are postmodern. Thus, many desituationisms concerning a
capitalist reality exist.

In the works of Smith, a predominant concept is the concept of
postpatriarchialist culture. The main theme of the works of Smith is the
dialectic, and subsequent failure, of textual society. Therefore, Bataille
promotes the use of material posttextual theory to challenge sexism.

If one examines realism, one is faced with a choice: either reject the
neocapitalist paradigm of narrative or conclude that class has objective value.
The subject is interpolated into a subdialectic conceptualist theory that
includes art as a paradox. In a sense, an abundance of discourses concerning
material posttextual theory may be discovered.

The subject is contextualised into a realism that includes culture as a
whole. It could be said that in Dogma, Smith reiterates the
neocapitalist paradigm of narrative; in Mallrats, although, he analyses
realism.

The primary theme of Long’s[4] essay on material
posttextual theory is a mythopoetical totality. Therefore, Sartre uses the term
‘realism’ to denote the role of the poet as observer.

If material posttextual theory holds, we have to choose between realism and
Batailleist `powerful communication’. But McElwaine[5]
suggests that the works of Smith are modernistic.

Precultural Marxism holds that narrativity is capable of intentionality, but
only if the premise of material posttextual theory is valid; if that is not the
case, Marx’s model of the neocapitalist paradigm of narrative is one of
“textual discourse”, and hence part of the futility of truth. However, the main
theme of the works of Tarantino is the bridge between society and sexual
identity.

If material posttextual theory holds, we have to choose between the
neocapitalist paradigm of narrative and postdialectic constructivist theory.
Thus, the characteristic theme of Humphrey’s[6] model of
premodern desublimation is a cultural whole.

The subject is interpolated into a neocapitalist paradigm of narrative that
includes narrativity as a totality. Therefore, Sargeant[7]
suggests that we have to choose between realism and postcapitalist dialectic
theory.

The subject is contextualised into a neotextual paradigm of reality that
includes sexuality as a reality. It could be said that Lyotard suggests the use
of the neocapitalist paradigm of narrative to attack class.

####. Material posttextual theory and conceptual theory

“Truth is used in the service of hierarchy,” says Lacan. If realism holds,
we have to choose between material posttextual theory and Marxist socialism.
However, the primary theme of the works of Pynchon is the common ground between
sexual identity and society.

“Consciousness is part of the meaninglessness of art,” says Debord; however,
according to Reicher[8] , it is not so much consciousness
that is part of the meaninglessness of art, but rather the rubicon, and
eventually the genre, of consciousness. Neodeconstructivist narrative implies
that class, somewhat paradoxically, has intrinsic meaning. In a sense, Sartre
uses the term ‘material posttextual theory’ to denote the defining
characteristic, and subsequent stasis, of dialectic sexual identity.

The main theme of Werther’s[9] analysis of conceptual
theory is the difference between class and sexual identity. Thus, Hanfkopf[10] states that we have to choose between material
posttextual theory and postsemanticist constructive theory.

A number of discourses concerning the role of the artist as poet exist.
However, Sontag uses the term ‘conceptual theory’ to denote not, in fact,
deappropriation, but predeappropriation.

If substructuralist narrative holds, we have to choose between material
posttextual theory and cultural postsemanticist theory. In a sense, Debord uses
the term ‘Derridaist reading’ to denote the absurdity of patriarchial class.

1. Werther, M. (1991) The Fatal
flaw of Class: Material posttextual theory and realism. And/Or
Press

2. Tilton, E. M. ed. (1988) Realism and material
posttextual theory. University of Massachusetts Press

3. Wilson, A. (1996) The Paradigm of Reality: Socialism,
realism and subcultural narrative. And/Or Press

4. Long, P. R. S. ed. (1989) Material posttextual theory
and realism. Yale University Press

5. McElwaine, K. O. (1971) The Reality of Genre: Realism
in the works of Tarantino. University of North Carolina Press

6. Humphrey, H. ed. (1990) Realism in the works of
McLaren. And/Or Press

7. Sargeant, W. N. V. (1978) Expressions of Collapse:
Realism in the works of Pynchon. University of Oregon Press

8. Reicher, J. ed. (1981) Realism, socialism and
precapitalist patriarchial theory. Loompanics

9. Werther, S. H. I. (1990) The Broken Door: Realism in
the works of Joyce. Oxford University Press

10. Hanfkopf, F. G. ed. (1974) Realism in the works of
Madonna. Loompanics

The essay you have just seen is completely meaningless and was randomly generated by the Postmodernism Generator. To generate another essay, follow this link.

The Postmodernism Generator was written by Andrew C. Bulhak using the Dada Engine, a system for generating random text from recursive grammars, and modified very slightly by Josh Larios (this version, anyway. There are others out there).

This installation of the Generator has delivered 18,487,273 essays since 25/Feb/2000 18:43:09 PST, when it became operational.

More detailed technical information may be found in Monash University Department of Computer Science Technical Report 96/264: “On the Simulation of Postmodernism and Mental Debility Using Recursive Transition Networks“.

More generated texts are linked to from the sidebar to the right.

If you enjoy this, you might also enjoy reading about the Social Text Affair, where NYU Physics Professor Alan Sokal’s brilliant(ly meaningless) hoax article was accepted by a cultural criticism publication. 
